services:
  db:
    image: mysql
    container_name: dbs_dev_app_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  db:
